import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/components/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import { ReduxProvider } from "@/lib/redux/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
        <ReduxProvider>
          {children}
        </ReduxProvider>
        </QueryProvider>
        <Toaster 
          position="bottom-center"
          theme="system" // or "dark", "system"
          expand={true} // show all toasts expanded
          visibleToasts={3} // max visible toasts
          toastOptions={{
            classNames: {
              toast: "text-center justify-center", 
            },
          }}
        />
      </body>
    </html>
  );
}
